# Generated by Django 5.1 on 2024-10-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_user_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submittedassignment',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
