# Generated by Django 5.1 on 2024-11-01 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_submittedassignment_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='user',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='auths.classroom'),
        ),
    ]
